[General]
input_dir = ./INPUT
output_dir = ./results
task = characterization

[Readquality]
seqkit_threads = 8

[Filter]
seqkit_threads = 8
cut_adapter = y
filter_quality = 7
filter_length = 1000
porechop_threads = 8

[Assembly]
flye_mode = nano-hq
flye_meta = y
flye_threads = 8
goldrush_genome_size = 300000
goldrush_min_read_length = 1000
goldrush_threads = 8
raven_threads = 8
shasta_read_length = 1000
shasta_threads = 8
wtdbg2_genome_size = 300000
wtdbg2_read_length = 1000
wtdbg2_kmer_fsize = 15
wtdbg2_kmer_psize = 0
wtdbg2_min_similarity = 0.05
wtdbg2_realign = y
wtdbg2_threads = 8
polish_threads = 2
checkv_db = ~/Documents/QPPL_offline/Databases/CheckV
checkv_threads = 8

[Characterization]
pharokka_threads = 8
pharokka_db = ~/Documents/QPPL_offline/Databases/Pharokka/pharokka_v1.8.0_databases
taxmyphage_threads = 8
taxmyphage_db = ~/Documents/QPPL_offline/Databases/taxmyPHAGE
phabox_db = ~/Documents/QPPL_offline/Databases/PhaBOX/phabox_db_v2_2
phabox_threads = 8
vhulk_location = ~/Documents/vHULK
vhulk_threads = 8
